name: Test pipeline

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: commit message
        env:
          COMMIT_MESSAGE: ${{ toJson(github.event.head_commit.message) }}
        run: echo "$COMMIT_MESSAGE"
