name: Test pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    steps:
      - uses: actions/checkout@v3
      - run: echo "deploying"
  test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test"
