name: Test pipeline

on:
  push:
    branches:
      - main
env:
  COMMIT_MESSAGE: github.event.head_commit.message

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: commit message
        run: echo "${{ toJSON(COMMIT_MESSAGE) }}"
