name: Test pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ !contains(join(github.event.commits.*.message, ', '), '#skip') }}
    steps:
      - uses: actions/checkout@v3
      - run: echo "deploying"
  tag_release:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - run: echo "tag/release"
